### PR TITLE
update to blockr 0.0.2 + styler

### PR DESCRIPTION
**Pull request by DivadNojnarg**
@JohnCoene Is this on purpose that `...` is never passed down to `new_block` in the different constructors?

### CODE REVIEW

**Comment by JohnCoene** [comment]
Probably an oversight on my part

**Comment by DivadNojnarg** [comment]
Ok I'll fix this.

**Comment by DivadNojnarg** [comment]
I am done with this one @JohnCoene

**Comment by JohnCoene** [comment]
Looks good

**Pull request merged**
